---

- name: install docker
  apt: 
    name: docker.io
    update_cache: yes

- name: add remote user to group docker
  command: usermod -aG docker {{ansible_user}}

- name: Start docker service
  service:
    name: docker
    state: restarted


