apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginxdemo
          image: k8s.gcr.io/nginx:1.7.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
