---

- hosts: master
  become: yes
  gather_facts: no
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: debug join_command_raw
      debug:
        msg: "{{ join_command_raw }}"
 
    - name: add join command to a dummy hostvar
      add_host:
        name: JOIN_CMD_HOLDER
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
  

- hosts: worker
  become: yes
  tasks:
    - name: debug node_join 
      debug:
        msg: "{{ hostvars['JOIN_CMD_HOLDER'].join_command }}"

    - name: clear node_join file if exists
      file:
        state: absent
        path: $HOME/node_joined.txt

    - name: join cluster
      shell: "{{ hostvars['JOIN_CMD_HOLDER'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
