---

- name: Update Helm repositories
  command: helm repo update

- name: Ensure helm values directory exists
  file:
    path: ~/helm/ingress_nginx
    state: directory

- name: Copy Helm values to host
  copy:
    src: files/helm-values.yaml
    dest: ~/helm/ingress_nginx/values.yaml

- name: Install/upgrade Nginx ingress controller
  command: >
    helm install --name nginx-ingress stable/nginx-ingress
      --namespace nginx-ingress
      --values ~/helm/ingress_nginx/values.yaml

#- name: Ensure Nginx ingress controller has started
#  command: kubectl -n nginx-ingress rollout status deployment nginx-ingress-controller

- name: Install firewalld
  tags: test
  become: yes
  package:
    name: firewalld
    state: present


- name: Allow external HTTP(S) traffic
  tags: test
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - http
    - https
