---

ca_config: "{{ cache_dir }}/ca-config.json"
pki_dir: /etc/kubernetes/pki
etcd_pki_dir: "{{ pki_dir }}/etcd"

# cluster ca path
ca: "{{ pki_dir }}/ca.pem"
ca_key: "{{ pki_dir }}/ca-key.pem"

# etcd certs path
etcd_ca: "{{ etcd_pki_dir }}/etcd-ca.pem"
etcd_ca_key: "{{ etcd_pki_dir }}/etcd-ca-key.pem"
etcd_cert: "{{ etcd_pki_dir }}/etcd.pem"
etcd_cert_key: "{{ etcd_pki_dir }}/etcd-key.pem"

# Kubernetes component certs path
kubelet: "{{ pki_dir }}/kubelet.pem"
kubelet_key: "{{ pki_dir }}/kubelet-key.pem"
admin: "{{ pki_dir }}/admin.pem"
admin_key: "{{ pki_dir }}/admin-key.pem"
apiserver: "{{ pki_dir }}/apiserver.pem"
apiserver_key: "{{ pki_dir }}/apiserver-key.pem"
scheduler: "{{ pki_dir }}/scheduler.pem"
scheduler_key: "{{ pki_dir }}/scheduler-key.pem"
controller_manager: "{{ pki_dir }}/controller-manager.pem"
controller_manager_key: "{{ pki_dir }}/controller-manager-key.pem"

# Kubernetes authenticating proxy cert path
front_ca: "{{ pki_dir }}/front-proxy-ca.pem"
front_ca_key: "{{ pki_dir }}/front-proxy-ca-key.pem"
front_client: "{{ pki_dir }}/front-proxy-client.pem"
front_client_key: "{{ pki_dir }}/front-proxy-client-key.pem"

# Kubernetes sa key path
sa_public_key: "{{ pki_dir }}/sa.pub"
sa_private_key: "{{ pki_dir }}/sa.key"
