---
- hosts: master
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: False
  vars:
    fpath: ~/demo-nginx/

  tasks:
  - name: Create directory
    file:
      path: "{{ fpath }}"
      state: directory

  - name: Upload the files
    copy:
      src: "{{ item }}"
      dest: "{{ fpath }}"
      mode: 0700
    with_fileglob:
      - ./templates/*

  - name: Create pod deployments and expose services
    command: "{{ fpath }}deploy.sh"

  - name: Get exposed port
    tags: getport
    command: "kubectl get svc {{k8s_nginx_svc_name}} --output=jsonpath='{range .spec.ports[0]}{.nodePort}'"
    register: result

  - set_fact:
      node_port: "{{ result.stdout }}"

  - debug: msg="Exposed port {{ node_port }}"



