---
- name: Create AWS resources
  hosts: local
  connection: local
  gather_facts: False
      
  tasks:
  - name: Create security group
    ec2_group:
      name: sg_http
      description: Ansible Security Group
      region: "{{aws_region}}"
      vpc_id: "{{vpc_id}}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: all
          cidr_ip: "{{my_local_cidr_ip}}"
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: sg_http

  - name: Create EC2 instance 
    ec2:
      key_name: "{{ project_name }}-{{ env }}-key"
      region: "{{aws_region}}"
      group_id: "{{sg_http.group_id}}"
      instance_type: "{{instance_type}}"
      image: "{{ami_id}}"
      wait: yes
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 100
          delete_on_termination: true
      exact_count: 1
      count_tag:
         Name: aws-ansible
      instance_tags:
         krole: "{{ item.krole }}"
         Name: "{{ item.krole }}{{ item.index }}"
         KubernetesCluster: "{{ k8s_cluster_name }}"
    register: ec2
    with_items: "{{ k8s_instances }}"
 
  - name: Add all instances to k8sDemo hosts group 
    add_host:
      name: "{{ item.1.public_ip }}"
      groups: 'k8sDemo'
    with_subelements: 
      - "{{ ec2.results }}"
      - instances
    when: item.1 | length > 0
 
  - name: Find ec2 facts
    ec2_remote_facts:
      region: "{{aws_region}}"
      filters:
        instance-state-name: running
        "tag:KubernetesCluster": "{{ k8s_cluster_name }}"
    register: instance_facts
 
  - name: Add instances to groups based on taged role.
    add_host:
      groups: "{{ item.0 }}"
      hostname: "{{ item.1 }}"
    with_together:
      - "{{ instance_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.krole')|list }}"
      - "{{ instance_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='public_ip_address')|list }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.1.public_ip }}"
      port: 22
      delay: 10
      timeout: 300
      state: started
    with_subelements:
      - "{{ ec2.results }}"    
      - instances
